name: Build Ionic App
on:
  push:
    branches: main

jobs:
  build:
    name: Debug Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ionic
        uses: coturiv/setyo-ionic@v1.0.4
        with:
          ionic-version: 7.2.0
      - name: Execute build
        run: | 
          ionic cordova build android --debug
 
